settings:
  permission: smadminlist.set
  font:
    zip-path: "/home/container/plugins/SMPS/modules/SM_AdminList/minecraft.zip"
    entry-path: ""

discord:
  webhook-url: "https://discord.com/api/webhooks/1474079129375604907/N2-9rcwruL0R8oKp7QJeM2Almnz_c5QxMD-qOjSd42g7EaPJVAD6tC7eSm70LMX6dohy"
  embed:
    title: "{action}: {player}"
    join-color: 3066993
    quit-color: 15158332
    footer: "SM_AdminList"
    action-field-name: ""
    action-field-value: ""
    list-field-name: "Список онлайна"
    image-title: "Игроки онлайн ({online}/{max})"
    online-format: "• {name}"
    empty-text: "Сейчас нет игроков онлайн."
    join-action: "Вход"
    quit-action: "Выход"
