name: DoAPI
version: '${version}'
main: net.schalker.DoAPI.DoAPI
api-version: '1.21'
folia-supported: true
description: DoAPI - Modular plugin framework for SchalkerMC
authors:
  - deforce_
dependencies:
  server:
    PlaceholderAPI:
      required: false
      load: BEFORE
    DiscordSRV:
      required: false
      load: BEFORE
    voicechat:
      required: false
      load: BEFORE
    InteractiveChatDiscordSrvAddon:
      required: false
      load: BEFORE
    LiteBans:
      required: false
      load: BEFORE
    LuckPerms:
      required: false
      load: BEFORE
