# Включает/выключает автосбор урожая мотыгой.
enabled: true

# Сколько единиц прочности тратит мотыга за одно автоматическое действие сбора урожая.
# Зачарование "Прочность" (Unbreaking) на мотыге, как и в ванили, снижает шанс
# реальной траты каждой отдельной единицы прочности.
durability-cost: 3
