settings:
  # Через сколько секунд предметы из списка ниже принудительно исчезнут с земли
  # (вместо ванильных 5 минут / 300 секунд).
  despawn-seconds: 30
  # Список предметов, для которых действует ускоренное исчезновение.
  items:
    - WHITE_CARPET
    - ORANGE_CARPET
    - MAGENTA_CARPET
    - LIGHT_BLUE_CARPET
    - YELLOW_CARPET
    - LIME_CARPET
    - PINK_CARPET
    - GRAY_CARPET
    - LIGHT_GRAY_CARPET
    - CYAN_CARPET
    - PURPLE_CARPET
    - BLUE_CARPET
    - BROWN_CARPET
    - GREEN_CARPET
    - RED_CARPET
    - BLACK_CARPET
    - STONE
    - COBBLESTONE
