commands:
  stream:
    enabled: true

luckperms:
  streamer-group: "streame"

notifications:
  broadcast-on-start: true
  discord:
    enabled: false
    webhook-url: ""
    username: "Stream Alert"
    avatar-url: "https://mc-heads.net/avatar/{player}/128"
    content: ""
    embed:
      enabled: true
      title: "{player} запустил стрим"
      description: "Смотреть: {link}"
      color: 9520895
      thumbnail-url: "https://mc-heads.net/avatar/{player}/128"

menu:
  title: "&[MAIN]Streamer Mode"

chat-filter:
  mask: "***"
  mask-links: true
  mask-ip: true
  # Relative to plugins/SMPS/modules/SM_StreamerMode/
  banned-words-file: "banned_words.txt"
